const string_table = {
  APP_NAVCOUNTER: 'Counter',
  APP_NAVDEBUG: 'Déboguer',
  APP_NAVFETCH: 'Aller chercher des données',
  APP_NAVFORM: 'Forme',
  APP_NAVHOME: 'Accueil',
  APP_NAVPROFILE: 'Profil',

  COUNTER_ADD: 'Ajouter compteur',
  COUNTER_CONTENT: 'Nombre actuel',
  COUNTER_DOCTITLE: 'Vous avez cliqué sur ${count} fois',
  COUNTER_HEADER: 'Counter',

  FORM_LASTNAME: 'Last Name',
  FORM_NAME: 'Name',
  FORM_REQUIRED: 'This field is required',
  FORM_SUBMIT: 'Submit',

  HOME_ALERT: "Il s'agit d'un contenu d'alerte subtile",
  HOME_HEADER: 'Salut tout le monde',
  HOME_SHOWALERT: "Afficher l'alerte",
  HOME_TEXT1: 'Cette application démontre plusieurs choses',
  HOME_TEXT2: "Il s'agit d'une application .net utilisant le service de conception pour rendre la page de base",
  HOME_TEXT3: 'Il contient également une application React rendant le contenu de la page',
  HOME_TEXT4: 'Il utilise également plusieurs contrôles et démontre la localisation',
  HOME_WELCOME: 'Bienvenue dans votre nouvelle application single - page',

  WEATHER_DATE: 'Date',
  WEATHER_DESCRIPTION: 'Ce composant démontre aller chercher des données à partir du serveur.',
  WEATHER_ERROR: 'Erreur lors de la récupération des données',
  WEATHER_HEADER: 'Prévisions Météo',
  WEATHER_REFRESH: 'Rafraîchir',
  WEATHER_SUMMARY: 'Résumé',
  WEATHER_TEMPC: 'Temp (c)',
  WEATHER_TEMPF: 'Temp (f)',
};
